### ISSUE TITLE
No such files as referred in readme - theme.js, theme.css 

### ISSUE THREAD

**Issue by romanr** [djonsson/jenkins-atlassian-theme#53]
Trying to install this self-hosted.

The instructions refer to  theme.js, theme.css  files which is not available. 
It appears you need to build it using grunt? 
It seems like you need to install:
- node
- npm
- grunt

All that just to build this Jenkins theme? It seems like a lot of effort for just a theme. 
Node, Npm , Grunt does not come standard with Debian for example and you have to build node from source. Just to use this Jenkins theme!
Or I am missing something? 
If not, can you please provide built package? Thank you!

**Comment by kansasSamurai** [comment]
workaround: Given that this is such a straight forward project, I was able to simply "build" each file from the command line like the following (it appeared to work):

cat *.js > theme.js
cat *.css > theme.css

I had to take that approach (before I stumbled on this issue/post) because the node.js install was broken for debian wheezy.
