### ISSUE TITLE
Broken footer in recent Jenkins builds

### ISSUE THREAD

**Issue by vikulin** [djonsson/jenkins-atlassian-theme#85]
Broken footer in recent Jenkins builds.

See screenshots.

Actual page footer:
![actual-footer](https://user-images.githubusercontent.com/743622/92507938-6f5d3780-f210-11ea-8f4c-5a406a93d2a6.png)

Expected page footer:
![expected-footer](https://user-images.githubusercontent.com/743622/92507970-7dab5380-f210-11ea-8a02-0413b6c057da.png)

**Comment by vikulin** [comment]
Links in Jenkins configuration:
![jenkins-theme](https://user-images.githubusercontent.com/743622/92508061-a895a780-f210-11ea-89e2-edc1a36d5c3b.png)

**Comment by kappa10j** [comment]
I'm experiencing the same issue.  Is this project being maintained?

**Comment by vikulin** [comment]
No, there are no changes since long time ago

пн, 21 сент. 2020 г. в 18:36, kappa10j <notifications@github.com>:

**Comment by kappa10j** [comment]
I assumed that was the case.  Do you know how to fix this?  I can make the changes locally.

**Comment by vikulin** [comment]
@kappa10j , fixed the issue. There are static links where the changes have been deployed:

https://vikulin.github.io/jenkins-atlassian-theme/theme.css

https://vikulin.github.io/jenkins-atlassian-theme/theme.js

**Comment by kappa10j** [comment]
Thank you.  It works nicely.  So what was the outcome of the meeting? From: Vadym VikulinSent: Monday, November 16, 2020 6:00 AMTo: djonsson/jenkins-atlassian-themeCc: kappa10j; MentionSubject: Re: [djonsson/jenkins-atlassian-theme] Broken footer in recent Jenkins builds (#85) @kappa10j , fixed the issue. There are static links where the changes have been deployed:https://vikulin.github.io/jenkins-atlassian-theme/theme.csshttps://vikulin.github.io/jenkins-atlassian-theme/theme.js—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
